version: 2

updates:
- package-ecosystem: "uv"
  directory: "/"
  target-branch: "main"
  schedule:
    interval: "weekly"
  groups:
    safe:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
    major:
      patterns:
        - "*"
      update-types:
        - "major"
