name: Code Style
description: Check code style

runs:
  using: "composite"
  steps:
    - name: ruff
      shell: bash
      run: |
        uv run ruff format --check
        uv run ruff check

    - name: ty
      shell: bash
      run: uv run ty check
